# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - ${ELASTIC_SEARCH_HOST:localhost}
  port: ${ELASTIC_SEARCH_PORT:9200}
  url_prefix:
  use_ssl: ${USE_SSL:True}
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: True
  http_auth:
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
